version: "3.9"

services:
  gitrepo_db_test:
    image: postgres:15.1-alpine
    container_name: gitrepo_db
    command: -p 5432
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-gitrepo:/var/lib/postgresql/data
    networks:
      - my-net
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-p", "5432" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    container_name: gitrepo-api
    command: ["./docker/app.sh"]
    ports:
      - "8000:8000"
    volumes:
      - ./app:/home/gitrepo/app
    networks:
      - my-net

  app_tests:
    build:
      context: .
    container_name: api_tests
    command: ["./docker/app_test.sh"]
    depends_on:
      gitrepo_db_test:
        condition: service_healthy
    volumes:
      - ./app:/home/restaurant/app
    networks:
      - my-net

volumes:
  db-gitrepo:
    driver: local


networks:
  my-net:
    external: true
