"""updated commits scheme

Revision ID: bdb37b7a0be4
Revises: f4b29e5eac87
Create Date: 2024-03-04 18:58:51.652521

"""
from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bdb37b7a0be4'
down_revision: str | None = 'f4b29e5eac87'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repository', 'position_cur',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('repository', 'position_prev',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repository', 'position_prev',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('repository', 'position_cur',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
